# Dealing with phylogenetic non-independence: a practical introduction. {#pseudorep}

This chapter will cover the most common use of phylogenetic comparative methods – dealing with phylogenetic non-independence. The focus here is on the key methods that will be used in practice and encountered in the literature. Practicality will be an overarching theme, with worked examples and links to online resources provided to help with this. We will also try to set the methods within wider, more familiar statistical frameworks (e.g. mixed models, other forms of non-independence) so that users can take advantage of pre-existing statistical understanding. Note that this is designed to aid readers familiar with these techniques; if readers are unfamiliar with them it will not substantially reduce their understanding.

•	What is phylogenetic non-independence? 
•	Phylogenetically independent contrasts (PICs) - the historical context of PCMs. 
•	Phylogenetic generalised least squares (PGLS). 
•	Related methods e.g. mixed models. 
•	Links to other kinds of non-independence, e.g. spatial, temporal.  
•	Emphasising the relationship to familiar statistics, e.g. regression, GLM, mixed models, meta-analysis. 
•	Online supplement linking to current software packages





## Phylogenetic signal
Phylogenetic signal is the pattern where close relatives have more similar trait values than more distant relatives (see Kamilar and Cooper 2013). 



Note that often people will mention that they "corrected for phylogeny" because of the phylogenetic signal in their variables. However, we **do not** correct for phylogeny because our variables show phylogenetic signal. We account for phylogenetic non-independence because the **residuals** from our models show phylogenetic signal (see Revell 2010). $\lambda$ shown in PGLS models above is the $\lambda$ for the model residuals **not** the individual variables. 