# A very brief introduction to diversification analyses

In this chapter we are going to very briefly introduce you to diversification analyses. Most introductory phylogenetic comparative methods courses cover this at least briefly, but a lot of the nuance lies beyond the scope of this *Primer*. If you need to use these kinds of methods for your analyses this should be a starting point for further reading and exploration. An excellent introduction can be found in Luke Harmon's book https://lukejharmon.github.io/pcm/chapters/.

## Why do we study species diversity?
Diversity, or species richness, is not evenly spread across the Tree of Life. Some groups have lots of species, while others have very few. A classic example is that of the animal phyla, where one single phylum, Arthropoda, has over 1 million species, while other phyla, for example Micrognathozoa (https://en.wikipedia.org/wiki/Limnognathia), have only one or a few species. This uneven diversity is found at all taxonomic levels; whether we look at species in phyla, or genera in families etc., we tend to see the same pattern. Some groups are more diverse than others. This has led to many biologists over the years trying to find out why this pattern exists. Is there something special about groups with lots of species? 

Many questions, predictions and hypotheses exist around uneven diversity. These form some of the most interesting and long lasting ideas in evolutionary biology.

###### HYPOTHESES and PICTURES????

There are many ways to test these kinds of hypotheses using phylogenetic comparative methods. We outline just a few below.

## Phylogenetic tree imbalance 
Although early investigations of diversity looked at how species were divided taxonomically, it's clear that species don't just spontaneously appear. Species evolve from other species, so accounting for phylogenetic relationships is really important. One of the easiest ways to investigate diversity on a phylogeny is to look at phylogenetic imbalance.

Phylogenetic imbalance occurs where sister clades on a phylogeny have different numbers of species. Phylogenies can vary from completely imbalanced (Fig 1 a) where one sister clade has one species and all the others are in the other clade, and fully balanced, where the two clades have an equal number of species (Fig 1 b). Some degree of imbalance is expected by chance in real phylogenies, so to measure how imbalanced a tree is we can compare it to a simulated trees with the same number of species.

####ADD FIGURE

There are a bunch of metrics for measuring phylogenetic imbalance reviewed Mooers and Heard 1997 which we won't expand on here.

## Birth death models and diversification rates
In recent years, rather than looking at tree shape to investigate uneven diversity across clades, it has become more common to look at diversification rates. Diversification is the rate of speciation minus the rate of extinction. Phylogenies give us an idea about both of these processes, though they're better at showing speciation than extinction in most cases (rabosky).

The simplest models for looking at this are birth death models, where the rate of speciation (birth; $\lambda$) and rate of extinction (death, $\mu$) combine to get a rate of diversification. We won't talk about these in detail here, but if you're interested there is an excellent introduction in https://lukejharmon.github.io/pcm/chapter10_birthdeath/. If diversification rates are high we tend to find phylogenies with lots of species. We often use a pure-birth model, i.e. a model where there is no extinction, just speciation, as a null model in diversification analyses. Under a pure-birth model we expect an exponential increase in the number of species through time. If there are interesting increases or decreases in diversification rate over time, our results should not fit the pure-birth null.

```{block, type = "info"}
Biologists love to reuse the same Greek letters over and over. $\lambda$ here is speciation rate. This is **not** the same as Pagel's $\lambda$.
```

## Lineage through time plots and the $\gamma$ statistic
One simple way to investigate diversification rates is to look at *lineage through time* or LTT plots. These show the number of lineages in a phylogeny at a given time on the y-axis, and the time on the x-axis. By convention we log transform the y-axis because under a pure-birth (i.e. no extinction) model the number of lineages should increase exponentially over time, so if we log this it gives us a nice straight line. LTT plots can be used to investigate changes in diversification rate in a phylogeny. If the plotted relationship is a straight line this indicates that lineage diversification is occurring at a constant rate through time (Fig a). Alternatively, an exponential curve suggests that diversification rates are increasing through time (fig b), and an asymptote suggests diversification rates are decreasing through time (fig c). Generally we'd compare these curves to simulated LTT plots assuming a pure-birth model to check whether the pattern we are seeing is significantly different to a pure-birth null model.

#### FIGURE

Rather than relying on an interpretation of these plots, Pybus and Harvey 2001 proposed using the $\gamma$ statistic instead. 

#### HOW DOES GAMMA WORK?

Similarly to other methods discussed in this chapter, the observed $\gamma$ statistic is compared to values obtained from pure-birth simulations. Significance is determined by seeing where the observed value falls within the distribution of values from the simulations. Significantly negative values of the $\gamma$ statistic suggest that rates of diversification have decreased through time, whereas the significantly positive values suggest that rates of diversification have increased through time.

More recently developed methods along a similar vein include TESS (Hoehna et al 2013) and TreePar (Stadler 2011).

## Diversification rate variation across branches
The methods above look across whole phylogenies, but many of the questions we have revolve around individual groups/clades within phylogenies. These simple models also estimate a single rate of speciation and extinction across a whole tree. Obviously this is a huge oversimplification; we expect lots of changes in rates, or **rate heterogeneity**, through time, especially across fairly large trees.

A large variety of methods have been developed that attempt to deal with this problem including MEDUSA (Alfaro et al. 2009), various methods in BayesTraits (ref), BAMM, and RevBayes. The method you are most likely to come across in the literature is BAMM, so we will briefly outline this here.

### BAMM!
BAMM (Bayesian Analysis of Macroevolutionary Mixtures; Rabosky et al 2014ab, Rabosky 2014) identifies discrete shifts in diversification rates at nodes of a tree (it can also investigate trait evolution but we will focus on diversification rates here), i.e places where diversification rates speed up or slow down. BAMM looks for rate shifts across the whole tree, so it can find 1, 2, 3 or more shifts. It does this using *reversible jump Markov Chain Monte Carlo* (i.e. Bayesian) methods to automatically explore a vast universe of possible models. It is biased towards simpler models (a common tactic in most evolutionary models - remember parsimony?) so rarely results in lots of rate shifts. 

For each MCMC run (generally over 1 million iterations are run in these analyses), BAMM simulates speciation and extinction along the tree, extracts the number of rate shifts, and then works out the probability of that particular combination of rate shifts occurring. The results BAMM outputs are a sample of all possible combinations across all models, in proportion to their posterior probability. The posterior, or distribution of results, from BAMM will thus contain lots of different combinations of rates and rate shifts, but will have those that occur more often across all the models appearing more often, than those that occur rarely appearing less often.

In the posterior, we call each of these possible combinations __distinct shift configurations__. These are the most probable configuration of shifts from __one model__ from the posterior. For example, one shift configuration may be a speed up at node 34 and a slow down at node 22 on model 10000. Each model in the posterior might have a different distinct shift configuration, or they might all be very similar. It depends on the dataset.

The number of possible distinct shift configurations is huge. Eventually if ran BAMM for for long enough you'd find a shift on every branch in the tree (because the branches can show shifts due to the effect of the prior alone).  

We know that all the distinct shift configurations are *possible* but they aren't equally *probable*. As mentioned above some may be common, and others rare. We need some way of summarising thousands of models, and taking this into account. There are two main approaches.

1. __Overall best shift configuration__
You can get this by looking at the maximum a posteriori (MAP) probability shift configuration, i.e. the one that appeared the most often in the posterior. This is a bit like using a consensus tree in phylogenetics. However, for most real datasets, the best rate shift configuration is merely one of a large number of possible rate shift configurations that have similar probabilities. So this method is not preferred (also if you've bothered to fit over 1 million models it seems pointless to just get one result!).

2. __Credible shift sets__
An alternative way to present the results is to summarise all the distinct shift configurations. However, not all distinct shift configurations are going to be significant. Therefore, BAMM splits shifts into "important" ones that help explain the data (core shifts) and ones that are less important (or likely just due to priors) using *marginal odds ratios*. Specifically, BAMM computes the marginal odds ratio for each rate shift for every branch in the phylogeny. It then excludes all shifts that are unimportant using a pre-determined threshold value (usually 5). The remaining shifts are the credible shift set. These are usually reported in papers using BAMM.

```{block, type = "warning"}
**Predictions are better than post-hoc stories.** BAMM is great, but it will often give answers you didn't expect. It is not a good idea to just run a BAMM analyses and see what happens. Most phylogenies will contain some rate shifts, but if you don't have hypotheses/predictions about what factors may influence diversification rates in your group then you'll be stuck trying to invent reasons for these rate shifts after the fact. This is not a great way to do science, and can lead to some very odd conclusions if you're just fishing around for ideas! Instead, thoroughly research your group, think about why some clades might diversify more rapidly than others, *then* run BAMM to see if your predictions are supported or not.
```

### Assumptions and issues with BAMM
Like all methods, BAMM has a number of important assumptions and issues. First, it assumes that evolutionary dynamics are described by _discrete_ shifts at nodes. It could equally be gradual changes along branches. BAMM cannot detect this, but neither can any other method. However it is worth remembering this when interpreting results, especially on long branches.

Second, the prior for the number of expected shifts will have a large effect on how many shifts are detected, particularly for long branches as the probability of seeing a shift due to the prior alone increases with branch length. To solve this BAMM estimates marginal odds ratios, scaling each marginal shift probability by the prior and branch length. You can (and should) check for this problem if you use BAMM.

Third, BAMM (and all other similar methods) gives inaccurate results for phylogenies with incomplete sampling, i.e. where you don't have every species in your phylogeny. 
This may be quite likely if you're working with invertebrates or plants or pretty much anything other than mammals and birds! If the sampling is non random, for example, you're missing a whole clade, the results will be even weirder. It's best to only use BAMM where you've got a fairly complete phylogeny.

Additionally, there has been a quite a lot of debate about the validity of BAMM in the literature recently. Moore et al. 2016 proposed several serious issues with BAMM, which basically boil down to two main points:

* BAMM outputs are highly sensitive the priors
* The likelihood function BAMM uses is wrong

Rabosky and colleagues have refuted these criticisms here: [http://bamm-project.org/prior.html], [http://bamm-project.org/replication.html], [http://bamm-project.org/developertoggle.html], [http://bamm-project.org/mea_likelihood.html], and [http://ift.tt/2m7qv6T].

There's no consensus just yet so use with caution, and be prepared to defend your choice to grumpy reviewers...

```{block, type = "warning"}
**Think about your sampling!** Diversification rate analyses are powerful, exciting, and fairly easy to implement. As such they're very tempting methods to use without really thinking carefully about the caveats, of which there are many! Incomplete sampling is a really big issue to consider. Sampling is generally incomplete and uneven; we never have every possible species in our phylogenies. If you only use living species, it is important to consider how extinct diversity may effect your conclusions. If you use living and fossil species you need to remember that for most groups (excluding Foraminifera apparently!) the fossil record is patchy at best. If species are missing at random this is less of a problem, but if you're missing a big chunk of diversity with a certain trait, or in a certain time period, your results may be meaningless at best, misleading at worst.
```

## Trait dependent diversification
Analyses of trait‐dependent diversification are used to detect whether particular traits promote high rates of diversification, leading to some clades becoming more diverse than others (Nee, May & Harvey 1994b). These kinds of analyses have been applied extensively in recent years to a variety of taxa and traits (e.g. Goldberg et al. 2010; Price et al. 2012; Givnish et al. 2014; Pyron & Burbrink 2014). Most use the binary state speciation and extinction model (BiSSE) and related methods (the original BiSSE paper Maddison, Midford & Otto (2007) has been cited 394 times; Google Scholar search 9 December 2015). However, Rabosky & Goldberg (2015) recently re‐evaluated the method and its assumptions and showed via simulations that a strong correlation between a trait and diversification rate can be inferred from a single diversification rate shift within a tree, even if the shift is unrelated to the trait of interest. They suggest that many examples of trait‐dependent diversification actually reflect this rate heterogeneity in trees and thus are biologically meaningless. Interestingly, these caveats are mentioned in earlier papers (Maddison, Midford & Otto 2007; FitzJohn 2010, 2012) but were seemingly not widely understood given the shock reaction to Rabosky & Goldberg (2015).

[CHAPTER ENDING MATERIAL STYLE STILL TBC BUT WILL BE CONSISTENT ACROSS THE BOOK]
## Summary

## Online materials

Online materials for this chapter are:
 - Diversification analyses

## MCQs

-----

## BOXES
